In [2]:
import pandas

In [3]:
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars,DayDiff,WeekDay,DiscountDiff,DiscountPerc
0,1,2015-07-17,2015-08-12,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3,26 days,Wednesday,138,11.714771
1,1,2015-07-17,2015-08-19,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3,33 days,Wednesday,131,11.769991
2,1,2015-07-17,2015-08-13,5,4370,4240,1,3,The Peninsula New York,5,27 days,Thursday,130,2.974828
3,1,2015-07-17,2015-07-26,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4,9 days,Sunday,72,4.140311
4,1,2015-07-17,2015-08-12,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4,26 days,Wednesday,67,3.852789

In [4]:
df["Snapshot Date"] = pandas.to_datetime(df["Snapshot Date"])

In [5]:
df["Checkin Date"] = pandas.to_datetime(df["Checkin Date"])

In [6]:
df["DayDiff"] = df["Checkin Date"] - df["Snapshot Date"]

In [7]:
df["WeekDay"] = df["Checkin Date"].dt.day_name()

In [8]:
df["DiscountDiff"] = df["Original Price"] - df["Discount Price"]

In [9]:
df["DiscountPerc"] = (df["DiscountDiff"] / df["Original Price"]) * 100

In [10]:
df.head()

,Snapshot ID,Snapshot Date,Checkin Date,Days,Original Price,Discount Price,Discount Code,Available Rooms,Hotel Name,Hotel Stars,DayDiff,WeekDay,DiscountDiff,DiscountPerc
0,1,2015-07-17,2015-08-12,5,1178,1040,1,6,Best Western Plus Seaport Inn Downtown,3,26 days,Wednesday,138,11.714771
1,1,2015-07-17,2015-08-19,5,1113,982,1,8,Best Western Plus Seaport Inn Downtown,3,33 days,Wednesday,131,11.769991
2,1,2015-07-17,2015-08-13,5,4370,4240,1,3,The Peninsula New York,5,27 days,Thursday,130,2.974828
3,1,2015-07-17,2015-07-26,5,1739,1667,1,18,Eventi Hotel a Kimpton Hotel,4,9 days,Sunday,72,4.140311
4,1,2015-07-17,2015-08-12,5,1739,1672,1,3,Eventi Hotel a Kimpton Hotel,4,26 days,Wednesday,67,3.852789

In [11]:
df.to_csv("Hotels_data_Changed.csv")

PermissionError: [Errno 13] Permission denied